# Generated by Django 2.1 on 2019-04-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.IntegerField()),
                ('q_id', models.IntegerField()),
                ('q_answer', models.CharField(max_length=500)),
                ('score', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=100)),
                ('creator', models.CharField(max_length=50)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('answer_user_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_title', models.CharField(max_length=200)),
                ('q_scope', models.CharField(max_length=50)),
                ('q_type', models.CharField(max_length=20)),
                ('q_content', models.CharField(max_length=500)),
                ('q_options', models.CharField(max_length=500)),
                ('q_standard_answer', models.CharField(max_length=500)),
            ],
        ),
    ]
