# Generated by Django 2.1 on 2019-04-09 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mars_api', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSystem',
            fields=[
                ('generalmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='mars_api.GeneralModel')),
                ('system_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('system_name', models.CharField(max_length=50)),
            ],
            bases=('mars_api.generalmodel',),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('generalmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mars_api.GeneralModel')),
                ('system_code', models.CharField(max_length=50)),
                ('resource_code', models.CharField(max_length=40)),
                ('resource_name', models.CharField(max_length=40)),
                ('resource_path', models.CharField(max_length=200)),
            ],
            bases=('mars_api.generalmodel',),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('generalmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mars_api.GeneralModel')),
                ('system_code', models.CharField(max_length=50)),
                ('role_code', models.CharField(max_length=50)),
                ('role_name', models.CharField(max_length=50)),
            ],
            bases=('mars_api.generalmodel',),
        ),
        migrations.CreateModel(
            name='RoleResource',
            fields=[
                ('generalmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mars_api.GeneralModel')),
                ('resource_code', models.CharField(max_length=40)),
                ('system_code', models.CharField(max_length=50)),
                ('role_code', models.CharField(max_length=50)),
            ],
            bases=('mars_api.generalmodel',),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('generalmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='mars_api.GeneralModel')),
                ('login_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('real_name', models.CharField(max_length=20)),
            ],
            bases=('mars_api.generalmodel',),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('generalmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mars_api.GeneralModel')),
                ('login_name', models.CharField(max_length=50)),
                ('system_code', models.CharField(max_length=50)),
                ('role_code', models.CharField(max_length=50)),
            ],
            bases=('mars_api.generalmodel',),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('login_name', 'system_code', 'role_code')},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['real_name'], name='general_use_real_na_fe1b75_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roleresource',
            unique_together={('resource_code', 'system_code', 'role_code')},
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['role_name'], name='general_rol_role_na_de51b3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('system_code', 'role_code')},
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['system_code', 'resource_code'], name='general_res_system__c1df3e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together={('system_code', 'resource_code')},
        ),
    ]
